# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_Caesar_DangGiaPhu_2380601694(object):
    def setupUi(self, Caesar_DangGiaPhu_2380601694):
        Caesar_DangGiaPhu_2380601694.setObjectName("Caesar_DangGiaPhu_2380601694")
        Caesar_DangGiaPhu_2380601694.resize(420, 292)
        self.centralwidget = QtWidgets.QWidget(Caesar_DangGiaPhu_2380601694)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 200, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 20, 301, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(90, 80, 301, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(90, 120, 301, 51))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        Caesar_DangGiaPhu_2380601694.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Caesar_DangGiaPhu_2380601694)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        Caesar_DangGiaPhu_2380601694.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Caesar_DangGiaPhu_2380601694)
        self.statusbar.setObjectName("statusbar")
        Caesar_DangGiaPhu_2380601694.setStatusBar(self.statusbar)

        self.retranslateUi(Caesar_DangGiaPhu_2380601694)
        QtCore.QMetaObject.connectSlotsByName(Caesar_DangGiaPhu_2380601694)

    def retranslateUi(self, Caesar_DangGiaPhu_2380601694):
        _translate = QtCore.QCoreApplication.translate
        Caesar_DangGiaPhu_2380601694.setWindowTitle(_translate("Caesar_DangGiaPhu_2380601694", "Caesar_DangGiaPhu_2380601694"))
        self.pushButton.setText(_translate("Caesar_DangGiaPhu_2380601694", "Decrypt"))
        self.pushButton_2.setText(_translate("Caesar_DangGiaPhu_2380601694", "Encrypt"))
        self.label.setText(_translate("Caesar_DangGiaPhu_2380601694", "Plain Text"))
        self.label_2.setText(_translate("Caesar_DangGiaPhu_2380601694", "Key"))
        self.label_3.setText(_translate("Caesar_DangGiaPhu_2380601694", "Cipher Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Caesar_DangGiaPhu_2380601694 = QtWidgets.QMainWindow()
    ui = Ui_Caesar_DangGiaPhu_2380601694()
    ui.setupUi(Caesar_DangGiaPhu_2380601694)
    Caesar_DangGiaPhu_2380601694.show()
    sys.exit(app.exec_())
